export function getTranslations() {
  return async function t(key) {
    // Retorna una traducción simulada basada en la clave
    const translations = {
      'productCard.featured': 'Destacado',
      'productCard.boost': 'Boost',
      'productCard.verified': 'Verificado',
      'home.hero.title1': 'Marketplace de Venezuela',
      'home.hero.title2': 'Compra y Vende Fácil',
      'home.hero.subtitle1': 'El marketplace más grande de Venezuela',
      'home.hero.subtitle2': 'Miles de vendedores verificados en',
      'home.hero.subtitle3': 'todo el país',
      'home.hero.featuredBadge': 'Destaca tus productos',
      'home.hero.featuredBadgeBold': 'desde $1 USD',
      'home.hero.publishFree': 'Publicar Gratis',
      'home.hero.seeHowToFeature': 'Ver cómo destacar',
      'home.hero.stats.activeProducts': 'Productos activos',
      'home.hero.stats.users': 'Usuarios',
      'home.hero.stats.featureFrom': 'Destacar desde',
      'home.freeBanner.title': 'Publicar es GRATIS',
      'home.freeBanner.subtitle': 'Publica productos sin costo',
      'home.freeBanner.compare': 'Comparar planes',
      'home.featured.wantToFeature': '¿Quieres destacar?',
      'home.featured.featureDesc': 'Aumenta la visibilidad de tus productos',
      'home.featured.seePackages': 'Ver paquetes',
      'home.featured.title': 'Productos Destacados',
      'home.featured.badge': '⭐ Destacados',
      'home.featured.emptyTitle': 'Sé el primero en destacar',
      'home.featured.emptyDesc': 'Destaca tus productos y aumenta las ventas',
      'home.featured.emptyPrice': 'Desde $1 USD',
      'home.featured.publishFree': 'Publicar gratis',
      'home.featured.seeCreditPackages': 'Ver paquetes de créditos',
      'home.boost.title': 'Aumenta la visibilidad de tus productos',
      'home.boost.subtitle': 'Elige el plan que mejor se adapte a tus necesidades',
      'home.boost.boost.name': 'Boost',
      'home.boost.boost.price': '$1',
      'home.boost.boost.desc': 'Aumenta la visibilidad de tus productos',
      'home.boost.boost.detail': 'Por solo $1 USD',
      'home.boost.featured24.popular': 'MÁS POPULAR',
      'home.boost.featured24.name': 'Destacado 24h',
      'home.boost.featured24.price': '$2',
      'home.boost.featured24.desc': 'Destaca tu producto por 24 horas',
      'home.boost.featured24.detail': 'Mayor visibilidad',
      'home.boost.featured48.name': 'Destacado 48h',
      'home.boost.featured48.price': '$4',
      'home.boost.featured48.desc': 'Destaca tu producto por 48 horas',
      'home.boost.featured48.detail': 'Máxima visibilidad',
      'home.boost.buyCredits': 'Comprar créditos',
      'home.categories.title': 'Categorías',
      'home.categories.subtitle': 'Encuentra lo que buscas',
      'home.categories.vehicles': 'Vehículos',
      'home.categories.vehiclesDesc': 'Carros, motos y más',
      'home.categories.tech': 'Tecnología',
      'home.categories.techDesc': 'Celulares, laptops y más',
      'home.categories.fashion': 'Moda',
      'home.categories.fashionDesc': 'Ropa, zapatos y más',
      'home.categories.homeCat': 'Hogar',
      'home.categories.homeCatDesc': 'Muebles, electrodomésticos y más',
      'home.categories.tools': 'Herramientas',
      'home.categories.toolsDesc': 'Herramientas y equipos',
      'home.categories.others': 'Otros',
      'home.categories.othersDesc': 'Más categorías',
      'home.trending.title': 'Trending',
      'home.trending.period': 'Últimos 7 días',
      'home.trending.views': 'vistas',
      'home.recent.title': 'Productos Recientes',
      'home.recent.viewAll': 'Ver todos',
      'home.recent.empty': 'No hay productos recientes',
      'home.recent.emptyCta': 'Sé el primero en publicar',
      'home.recent.publishFree': 'Publicar gratis',
      'home.cta.title': '¿Listo para vender?',
      'home.cta.subtitle': 'Publica tu primer producto gratis',
      'home.cta.publishNow': 'Publicar ahora',
      'home.cta.featureAd': 'Destacar anuncio',
    };
    return translations[key] || key;
  };
}